version: '3'

volumes:
  sock:

services:
  mysql:
    image: yobasystems/alpine-mariadb
    expose:
      - "3306"
    volumes:
      - "/srv/pushjet/mysql:/var/lib/mysql"
    deploy:
      restart_policy: 
        condition: on-failure
    restart: unless-stopped
    env_file:
      - .env
  nginx:
    build:
      context: .
      dockerfile: conf/Dockerfile.nginx
    image: pushjetserver_nginx:latest
    deploy:
      restart_policy: 
        condition: on-failure
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - "/srv/pushjet/http:/srv/pushjet"
    env_file:
      - .env
  pushjetapi:
    build:
      context: .
      dockerfile: conf/Dockerfile.pushjetapi
    image: pushjetserver_pushjetapi:latest
    deploy:
      restart_policy: 
        condition: on-failure
    restart: unless-stopped
    volumes:
      - "sock:/srv/sock"
    env_file:
      - .env
