from os import environ

MYSQL_ROOT_PASSWORD = environ['MYSQL_ROOT_PASSWORD']
MYSQL_DATABASE = environ['MYSQL_DATABASE']
MYSQL_USER = environ['MYSQL_USER']
MYSQL_PASSWORD = environ['MYSQL_PASSWORD']
GOOGLE_API_KEY = environ['GOOGLE_API_KEY']
GOOGLE_GCM_SENDER_ID = environ['GOOGLE_GCM_SENDER_ID']
